name: Build and Release

on:
  push:
    branches:
    - main
  workflow_dispatch:
  repository_dispatch:
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: 5nafu/hcloud-doorkeeper-action@environment
      with:
        hcloud_token: ${{ secrets.hcloud_token }}
        firewall_name: test
        port: 1234
        protocol: tcp
    - run: sleep 30s
      shell: bash
