name: Build and Release

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
  repository_dispatch:
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: GH_Token
      run: echo ${{ secrets.GITHUB_TOKEN }} | base64
