name: Tag release
on:
  push:
    branches:
    - main
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
