name: Docker Image CI
on:
  push:
    tags:
    - "v.*.*.*"
  pull_request:
    branches:
    - 'main'
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - id: tag_version_split
      if: github.event_name != 'pull_request'
      run:
        tag=${GITHUB_REF/refs\/tags\//}
        major=$(echo $tag | cut -d. -f1)
        echo "::set-output name=major::$major"
        minor=$(echo $tag | cut -d. -f2)
        echo "::set-output name=minor::$minor"
        patch=$(echo $tag | cut -d. -f3)
        echo "::set-output name=patch::$patch"
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
          # list of Docker images to use as base name for tags
          images: |
            docker.pkg.github.com/idealo/compute-github-runner-dind-shell-operator/compute-github-runner-dind-shell-operator
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
    - name: DEBUG Docker meta
      run: |
        echo "Tags: ${{ steps.meta.outputs.tags }}"
        echo "Labels: ${{ steps.meta.outputs.labels }}"
    - name: DEBUG version_split
      if: github.event_name != 'pull_request'
      run: |
        echo "Delete: ~${{ steps.tag_version_split.outputs.major }}.${{ steps.tag_version_split.outputs.minor }}.0"
